package vn.kpi.constants;

public class Constant {
    public static final Integer SIZE_PARTITION = 999;

    public interface RESOURCES {
        String INDICATOR = "INDICATOR";
        String INDICATOR_CONVERSION = "INDICATOR_CONVERSION";
        String WORK_PLANNING_TEMPLATE = "WORK_PLANNING_TEMPLATE";
        String ORGANIZATION_EVALUATION = "ORGANIZATION_EVALUATION";
        String EMPLOYEE_EVALUATIONS = "EMPLOYEE_EVALUATIONS";
        String ORGANIZATION_EVALUATE = "ORGANIZATION_EVALUATE";
        String EMPLOYEE_KPI_SUMARY = "EMPLOYEE_KPI_SUMARY";
        String ORGANIZATION_SUMMARY = "ORGANIZATION_SUMMARY";
        String PERSONAL_EVALUATE = "PERSONAL_EVALUATE";
        String EMPLOYEE_EVALUATE = "EMPLOYEE_EVALUATE";
        String INDICATOR_SCOPES = "INDICATOR_SCOPES";
        String ORGANIZATION_INDICATORS = "ORGANIZATION_INDICATORS";
        String EVALUATION_PERIODS = "EVALUATION_PERIODS";
        String ORGANIZATION_WORK_PLANNINGS = "ORGANIZATION_WORK_PLANNINGS";
        String EMPLOYEE_INDICATORS = "EMPLOYEE_INDICATORS";
        String EMPLOYEE_WORK_PLANNINGS = "EMPLOYEE_WORK_PLANNINGS";
        String PERSONAL_EVALUATIONS = "PERSONAL_EVALUATIONS";
        String KPI_ORG_CONFIGS = "KPI_ORG_CONFIGS";
        String ORGANIZATION_AGGREGATE_DATA = "ORGANIZATION_AGGREGATE_DATA";
        String KPI_EXPORT = "KPI_EXPORT";
        String ORGANIZATION_PROVIDE_LEVEL1 = "ORGANIZATION_PROVIDE_LEVEL1";
    }

    public interface XepLoaiConstant {
        Long TY_LE_VUOT_DAY_MANH = 1L;
        Long TONG_TRONG_SO_VUOT_DAY_MANH = 2L;
        Long MUC_VUOT_SO_VOI_DAY_MANH = 3L;
        Long KHCT_DON_VI = 4L;
        Long TY_LE_VUOT_MUC_KHCT = 5L;
        Long TY_LE_KHONG_HOAN_THANH_KHCT = 6L;
        Long TONG_SO_GIO_GIANG = 7L;
        Long TY_LE_VUOT_MUC_CBQT = 8L;
        Long TY_LE_VUOT_MUC_CBTC = 9L;
        Long PHAT_TRIEN_DAO_TAO = 10L;
        Long KIEM_DINH_DAI_HOC = 11L;
        Long KIEM_DINH_THAC_SI = 12L;
        Long TY_LE_TOT_NGHIEP_DUNG_HAN = 13L;
        Long SO_GIANG_VIEN_DAT_NN = 14L;
        Long SO_GIANG_VIEN_BAO_VE_LATS = 15L;
    }

    public interface CATEGORY_TYPES {
        String LOAI_HINH_DON_VI = "HR_LOAI_HINH_DON_VI";
        String DON_VI_TINH = "KPI_DON_VI_TINH";
        String CACH_DANH_GIA = "KPI_CACH_DANH_GIA";
        String CAP_KPI = "KPI_LEVEL";
        String CHU_KY = "KPI_CHU_KY";
        String PHAN_LOAI = "KPI_PHAN_LOAI";
        String LOAI_DANH_GIA = "KPI_LOAI_DANH_GIA";
        String DKY_MUC_TIEU_DON_VI = "KPI_DKY_MUC_TIEU_DON_VI";
        String INDICATOR_CONVERSION_STATUS = "INDICATOR_CONVERSION_STATUS";
        String KPI_LEVEL_COMPLETE = "KPI_LEVEL_COMPLETE";
        String HOC_HAM = "HR_HOC_HAM";
        String LOAI_TO_CHUC_CTR_XH = "LOAI_TO_CHUC_CTR_XH";
        String CHUC_DANH_CTR_XH = "CHUC_DANH_CTR_XH";
        String KPI_DKY_MUC_TIEU_DON_VI = "KPI_DKY_MUC_TIEU_DON_VI";
        String TRINH_DO_DAO_TAO = "TRINH_DO_DAO_TAO";
        String KPI_EMPLOYEE_EVALUATION_STATUS = "KPI_EMPLOYEE_EVALUATION_STATUS";
        String KPI_ORGANIZATION_EVALUATION_STATUS = "KPI_ORGANIZATION_EVALUATION_STATUS";
        String KPI_PHAN_NHOM = "KPI_PHAN_NHOM";
        String HR_LOAI_HINH_DON_VI = "HR_LOAI_HINH_DON_VI";
        String STATUS_KPI_LEVEL1 = "STATUS_KPI_LEVEL1";
    }

    public interface ATTRIBUTE_CODE {
        String ORG_IDS = "ORG_IDS";
    }

    public interface STATUS {
        String KO_DG = "KO_DG";
        String DU_THAO = "DU_THAO";
        String XAC_NHAN = "XAC_NHAN";
        String PHE_DUYET = "PHE_DUYET";
        String LAP_DANH_SACH = "LAP_DANH_SACH";
        String CHOT_DU_LIEU1 = "CHOT_DU_LIEU1";
        String CHOT_DU_LIEU2 = "CHOT_DU_LIEU2";
        String CHOT_KET_QUA = "CHOT_KET_QUA";
        String DANH_GIA = "DANH_GIA";
        String KHOI_TAO = "KHOI_TAO";
        String YC_NHAP_LAI = "YC_NHAP_LAI";
        String CHO_PHE_DUYET = "CHO_PHE_DUYET";
        String QLTT_DANH_GIA = "QLTT_DANH_GIA";
        String CHO_PHE_DUYET_HIEU_LUC_LAI = "CHO_PHE_DUYET_HIEU_LUC_LAI";
        String YC_DANH_GIA_LAI = "YC_DANH_GIA_LAI";
        String CHO_QLTT_DANH_GIA = "CHO_QLTT_DANH_GIA";
        String DA_XAC_NHAN_KQ_DANH_GIA = "DA_XAC_NHAN_KQ_DANH_GIA";
        String CHO_QLTT_DANH_GIA_LAI = "CHO_QLTT_DANH_GIA_LAI";
        String CHOT_KQ_DANH_GIA = "CHOT_KQ_DANH_GIA";
    }

}
